#!/bin/sh
#-------------------------------------------------------------------------------------------------#
# AUTHOR:  Andrew Michaud - https://andrewmichaud.com                                             #
# FILE:    aliases                                                                                #
# PURPOSE: Shell aliases definition file.                                                         #
# UPDATED: 2018-03-08                                                                             #
# LICENSE: ISC                                                                                    #
#-------------------------------------------------------------------------------------------------#
# Useful aliases.
alias betrsync="rsync -azvh --progress --partial"
alias df="df -h"
alias dir="ls -Cb"
alias du="du -ch"
alias feh="feh --no-fehbg"
alias nview="nvim -R"
alias vdir="ls -Cb"
alias view="nvim -R"

# Safety aliases.
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"

# Silly aliases.
alias justice="wget -qO- 'https://andrewmichaud.com/justice.ogg' | mpv --really-quiet -"
alias git-yolo='git commit -am "$(curl -s http://whatthecommit.com/index.txt)"'
alias starwars="telnet towel.blinkenlights.nl"
alias whence="which"
alias whom="who"

# Force XDG_BASE_DIRECTORY_SPEC conformation on various apps.
alias gimp="gimp -g \${XDG_CONFIG_HOME}/gimp/config"
alias gpg="gpg --homedir \${XDG_CONFIG_HOME}/gnupg"
alias gpg2="gpg2 --homedir \${XDG_CONFIG_HOME}/gnupg"
alias jshint="jshint --config \${XDG_CONFIG_HOME}/jshint/jshintrc"
alias mutt="mutt -F \${XDG_CONFIG_HOME}/mutt/muttrc"
alias offlineimap="offlineimap -c \${XDG_CONFIG_HOME}/offlineimap/config"
alias startx="startx \${XDG_CONFIG_HOME}/X11/xinitrc"
alias svn="svn --config-dir \${XDG_CONFIG_HOME}/subversion"
alias tmux="tmux -2 -f \${XDG_CONFIG_HOME}/tmux/tmux.conf"
alias wget="wget --hsts-file=\${XDG_CACHE_HOME}/wget/hstsdb"

# Neovim now defaults to init.vim, so I default to that.
alias vim="vim -u \${XDG_CONFIG_HOME}/vim/init.vim"
