#!/bin/sh
#-------------------------------------------------------------------------------------------------#
# AUTHOR:  Andrew Michaud - https://andrewmichaud.com                                             #
# FILE:    linux                                                                                  #
# PURPOSE: Linux-specific shell nonsense definition file.                                         #
# UPDATED: 2016-07-06                                                                             #
# LICENSE: ISC                                                                                    #
#-------------------------------------------------------------------------------------------------#
# XDG dirs.
[ -z "$XDG_CONFIG_HOME" ] && export XDG_CONFIG_HOME="$HOME/.config"
[ -z "$XDG_CACHE_HOME" ] && export XDG_CACHE_HOME="$HOME/.cache"
[ -z "$XDG_DATA_HOME" ] && export XDG_DATA_HOME="$HOME/.local/share"
[ -z "$XDG_RUNTIME_DIR" ] && export XDG_RUNTIME_DIR="/run/user/1000"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# pbcopy/pbpaste > xclip
alias pbcopy="xclip -selection clipboard"
alias pbpaste="xclip -selection clipboard -o"

# Ensure ssh-agent is set up and will run.
if ! pgrep ssh-agent > /dev/null; then
    ssh-agent > "$XDG_RUNTIME_DIR/ssh/agent"
fi

if [ "$SSH_AGENT_PID" = "" ]; then
    mkdir -p "$XDG_RUNTIME_DIR/ssh"
    ssh-agent > "$XDG_RUNTIME_DIR/ssh/agent"
    eval "$(cat "$XDG_RUNTIME_DIR/ssh/agent")"
fi

ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'
