#!/bin/sh
#-------------------------------------------------------------------------------------------------#
# AUTHOR:  Andrew Michaud - https://andrewmichaud.com                                             #
# FILE:    posix                                                                                  #
# PURPOSE: POSIX-specific (not counting OS X for Reasons) shell nonsense definition file.         #
# UPDATED: 2018-03-20                                                                             #
# LICENSE: ISC                                                                                    #
#-------------------------------------------------------------------------------------------------#
# XDG dirs.
[ -z "$XDG_CONFIG_HOME" ] && export XDG_CONFIG_HOME="$HOME/.config"
[ -z "$XDG_CACHE_HOME" ] && export XDG_CACHE_HOME="$HOME/.cache"
[ -z "$XDG_DATA_HOME" ] && export XDG_DATA_HOME="$HOME/.local/share"

if [ -z "$UID" ]; then
    UID=$(id -u)
fi

# GNU/Linux specific.
# TODO should add some check for RUNTIME specifically - it's not just a Linux/BSD thing.
if [ "$(uname -s)" = "Linux" ]; then
    alias l="ls -CFh --color=auto"
    alias la="ls -Ah --color=auto"
    alias ll="ls -alh --color=auto"
    alias lt="ls -alht --color=auto"

    # Set LS_COLORS.
    eval "$(dircolors "$XDG_CONFIG_HOME"/colors/dircolors.256dark)"

# BSD specific.
else
    alias l="ls -CFhG"
    alias la="ls -AhG"
    alias ll="ls -alhG"
    alias lt="ls -alhtG"
fi

if touch "/run/user/$UID"; then
    export XDG_RUNTIME_DIR="/run/user/1000"
elif touch "/tmp/test"; then
    mkdir -p "/tmp/$UID"
    export XDG_RUNTIME_DIR="/tmp/$UID"
else
    mkdir -p "$HOME/xdg_runtime"
    export XDG_RUNTIME_DIR="$HOME/xdg_runtime"
fi

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# pbcopy/pbpaste > xclip
alias pbcopy="xclip -selection clipboard"
alias pbpaste="xclip -selection clipboard -o"

# Ensure ssh-agent is set up and will run.
mkdir -p "$XDG_RUNTIME_DIR/ssh"
if ! pgrep ssh-agent > /dev/null; then
    ssh-agent > "$XDG_RUNTIME_DIR/ssh/agent"
fi

if [ "$SSH_AGENT_PID" = "" ]; then
    ssh-agent > "$XDG_RUNTIME_DIR/ssh/agent"
    eval "$(cat "$XDG_RUNTIME_DIR/ssh/agent")"
fi

ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'
