#!/bin/sh

. "$HOME/.config/shell/linux"

# Update Xresources.
[ -f .Xresources ] && xrdb -merge .Xresources

# Set cursor style and auto-hide cursor.
xsetroot -cursor_name left_ptr
unclutter &

# Run scripts.
[ -f "$XDG_DATA_HOME/bin/setWallpaper" ] && "$XDG_DATA_HOME/bin/setWallpaper" &
[ -f "$XDG_DATA_HOME/bin/fixscreens" ] && "$XDG_DATA_HOME/bin/fixscreens" &

# dbus and agents.
eval "$(dbus-launch --auto-syntax)"

# Launch programs I want running.
pgrep -x xscreensaver | xscreensaver -no-splash &
pgrep -x pidgin | pidgin &
pgrep -x mpd | mpd &
pgrep -x mate-power-manager | mate-power-manager &
pgrep -x dunst | dunst &

# Launch Taffybar and XMonad.
taffybar &
