#!/bin/sh

if [[ "$(uname -s)" == "Darwin" ]]; then
    . "$HOME/Library/Preferences/shell/osx"
elif [[ "$(uname -s)" == "Linux" ]]; then
    . "$HOME/.config/shell/linux"
fi

# Update Xresources.
[ -f .Xresources ] && xrdb -merge .Xresources

# Set cursor style and auto-hide cursor.
xsetroot -cursor_name left_ptr
unclutter &

xscreensaver -no-splash &

# Run scripts.
[ -f "$XDG_DATA_HOME/bin/setWallpaper" ] && "$XDG_DATA_HOME/bin/setWallpaper" &
[ -f "$XDG_DATA_HOME/bin/fixscreens" ] && "$XDG_DATA_HOME/bin/fixscreens" &

# dbus and agents.
eval "$(dbus-launch --auto-syntax)"
eval "$(ssh-agent)"
export SSH_ASKPASS=ssh-askpass
eval "$(gnome-keyring-daemon)"

# Launch programs I want running.
# Chat, music, power management, notifications.
pgrep -x pidgin | pidgin &
pgrep -x mopidy | mopidy &
pgrep -x mate-power-manager | mate-power-manager &
pgrep -x dunst | dunst &

# Launch Taffybar and XMonad.
taffybar &
exec xmonad
