#!/bin/sh
#-------------------------------------------------------------------------------------------------#
# AUTHOR:  Andrew Michaud                                                                         #
#          https://andrewmichaud.com                                                              #
# FILE:    aliases                                                                                #
# PURPOSE: Shell aliases definition file.                                                         #
# UPDATED: 2015-08-27                                                                             #
# LICENSE: MIT/BSD                                                                                #
#-------------------------------------------------------------------------------------------------#

# Useful aliases.
alias df="df -h"
alias du="du -ch"
alias grep="grep --color=auto"
alias l="ls -CFh"
alias la="ls -Ah"
alias ll="ls -alh"

# Safety aliases.
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# Silly aliases.
alias git-yolo='git commit -am "$(curl -s http://whatthecommit.com/index.txt)"'
alias starwars="telnet towel.blinkenlights.nl"
alias whence="which"

# Force XDG_BASE_DIRECTORY_SPEC conformation on various apps.
alias feh="feh --no-fehbg"
alias firefox="firefox --profile \${XDG_CONFIG_HOME}/firefox"
alias gimp="gimp -g \${XDG_CONFIG_HOME}/gimp/config"
alias mpdscribble="mpdscribble --conf \${XDG_CONFIG_HOME}/mpdscribble/config \
--log \${XDG_CACHE_HOME}/mpdscribble/mpdscribble.log"
alias ncmpcpp="ncmpcpp -c \${XDG_CONFIG_HOME}/ncmpcpp/config"
alias nvim="nvim -u \${XDG_CONFIG_HOME}/nvim/config.vim"
alias pip="pip --log-file \${XDG_CACHE_HOME}/pip/pip.log --cache-dir \${XDG_CACHE_HOME}/pip"
alias startx="startx \${XDG_CONFIG_HOME}/X11/xinitrc"
alias svn="svn --config-dir \${XDG_CONFIG_HOME}/subversion"
alias tmux="TERM=xterm-256color tmux -f \${XDG_CONFIG_HOME}/tmux/config"
alias view="view -u \${XDG_CONFIG_HOME}/vim/config.vim"
alias vim="vim -u \${XDG_CONFIG_HOME}/vim/config.vim"
