#!/bin/sh  #--------------------------------------------------------------------------------------#
# AUTHOR:  Andrew Michaud                                                                         #
#          https://andrewmichaud.com                                                              #
# FILE:    aliases                                                                                #
# PURPOSE: Shell aliases definition file.                                                         #
# UPDATED: 2016-03-09                                                                             #
# LICENSE: ISC                                                                                    #
#-------------------------------------------------------------------------------------------------#

# Useful aliases.
alias df="df -h"
alias du="du -ch"
alias feh="feh --no-fehbg"
alias grep="grep --color=auto"
alias l="ls -CFh"
alias la="ls -Ah"
alias ll="ls -alh"
alias lt="ls -alht"
alias nview="nvim -R"
alias view="nvim -R"

# Safety aliases.
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# Silly aliases.
alias git-yolo='git commit -am "$(curl -s http://whatthecommit.com/index.txt)"'
alias starwars="telnet towel.blinkenlights.nl"
alias whence="which"
alias whom="who"

# Force XDG_BASE_DIRECTORY_SPEC conformation on various apps.
alias firefox="firefox --profile \${XDG_CONFIG_HOME}/firefox"
alias gimp="gimp -g \${XDG_CONFIG_HOME}/gimp/config"
alias gpg="gpg --homedir \${XDG_CONFIG_HOME}/gnupg"
alias gpg2="gpg2 --homedir \${XDG_CONFIG_HOME}/gnupg"
alias jshint="jshint --config \${XDG_CONFIG_HOME}/jshint/jshintrc"
alias mpdscribble="mpdscribble --conf \${XDG_CONFIG_HOME}/mpdscribble/config \
--log \${XDG_CACHE_HOME}/mpdscribble/mpdscribble.log"
alias ncmpcpp="ncmpcpp -c \${XDG_CONFIG_HOME}/ncmpcpp/config"
alias pip="pip --log-file \${XDG_CACHE_HOME}/pip/pip.log --cache-dir \${XDG_CACHE_HOME}/pip"
alias startx="startx \${XDG_CONFIG_HOME}/X11/xinitrc"
alias svn="svn --config-dir \${XDG_CONFIG_HOME}/subversion"
alias tmux="tmux -2 -f \${XDG_CONFIG_HOME}/tmux/tmux.conf"

# Neovim now defaults to init.vim, so I default to that.
alias vim="vim -u \${XDG_CONFIG_HOME}/vim/init.vim"
