#!/bin/sh
#-------------------------------------------------------------------------------------------------#
# AUTHOR:  Andrew Michaud - https://andrewmichaud.com                                             #
# FILE:    linux                                                                                  #
# PURPOSE: Linux-specific shell nonsense definition file.                                         #
# UPDATED: 2016-04-22                                                                             #
# LICENSE: ISC                                                                                    #
#-------------------------------------------------------------------------------------------------#
[ -z "$XDG_CONFIG_HOME" ] && export XDG_CONFIG_HOME="$HOME/.config"
[ -z "$XDG_CACHE_HOME" ] && export XDG_CACHE_HOME="$HOME/.cache"
[ -z "$XDG_DATA_HOME" ] && export XDG_DATA_HOME="$HOME/.local/share"


# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# Ensure ssh-agent is set up and will run.
if ! pgrep ssh-agent > /dev/null; then
    ssh-agent > "$XDG_RUNTIME_DIR/ssh/agent"
fi

if [ "$SSH_AGENT_PID" = "" ]; then
    eval "$(cat "$XDG_RUNTIME_DIR/ssh/agent")"
fi

ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'
