#!/bin/sh

alias ls="ls -FG"
export PATH="/usr/local/bin:$PATH"

# XDG base spec.  OS-independent, theoretically.
export XDG_CONFIG_HOME="$HOME/Library/Preferences"
export XDG_DATA_HOME="$HOME/Library"
export XDG_CACHE_HOME="$HOME/Library/Caches"
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
export XDG_CONFIG_DIRS="/etc/xdg"
