#!/bin/sh
#-------------------------------------------------------------------------------------------------#
# AUTHOR:  Andrew Michaud - https://andrewmichaud.com                                             #
# FILE:    osx                                                                                    #
# PURPOSE: OSX-specific shell nonsense definition file.                                           #
# UPDATED: 2016-04-22                                                                             #
# LICENSE: ISC                                                                                    #
#-------------------------------------------------------------------------------------------------#
# XDG dirs.
export XDG_CONFIG_HOME="$HOME/Library/Preferences"
export XDG_CACHE_HOME="$HOME/Library/Caches"
export XDG_DATA_HOME="$HOME/Library"

PATH="/usr/local/sbin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"

MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
