#!/bin/sh

export XDG_CONFIG_HOME="$HOME/Library/Preferences"
export XDG_CACHE_HOME="$HOME/Library/Caches"
export XDG_DATA_HOME="$HOME/Library"
export XDG_RUNTIME_DIR="/tmp/$USER/"

alias ls="ls -FG"
