#!/bin/sh

# Color grep and ls.  Works on mac and linux.
alias grep="grep --color=auto"

# Useful aliases.
alias ll="ls -al"
alias rm="rm -i"
alias la="ls -A"
alias l="ls -CF"
alias df="df -h"
alias du="du -c -h"

# Safety features.
alias cp="cp -i"
alias mv="mv -i"

alias whence="which"
alias starwars='telnet towel.blinkenlights.nl'
alias git-yolo='git commit -am "`curl -s http://whatthecommit.com/index.txt`"'
