#!/bin/bash

# tput nonsense
export P_RESET="$(tput sgr0)"

# 16 colors should be enough for anyone.
if [ "$(tput colors)" = "16" ]; then
    export P_BASE03="$(tput setaf 0)"
    export P_BASE02="$(tput setaf 1)"
    export P_BASE01="$(tput setaf 2)"
    export P_BASE00="$(tput setaf 3)"
    export P_BASE0="$(tput setaf 4)"
    export P_BASE1="$(tput setaf 5)"
    export P_BASE2="$(tput setaf 6)"
    export P_BASE3="$(tput setaf 7)"
    export P_YELLOW="$(tput setaf 10)"
    export P_ORANGE="$(tput setaf 9)"
    export P_RED="$(tput setaf 8)"
    export P_MAGENTA="$(tput setaf 15)"
    export P_VIOLET="$(tput setaf 14)"
    export P_BLUE="$(tput setaf 13)"
    export P_CYAN="$(tput setaf 12)"
    export P_GREEN="$(tput setaf 11)"

# Hopefully we have at least 8 colors.
else
    export P_BASE03="$(tput setaf 4)"
    export P_BASE02="$(tput setaf 4)"
    export P_BASE01="$(tput setaf 7)"
    export P_BASE00="$(tput setaf 7)"
    export P_BASE0="$(tput setaf 6)"
    export P_BASE1="$(tput setaf 4)"
    export P_BASE2="$(tput setaf 7)"
    export P_BASE3="$(tput setaf 7)"
    export P_YELLOW="$(tput setaf 3)"
    export P_ORANGE="$(tput setaf 3)"
    export P_RED="$(tput setaf 1)"
    export P_MAGENTA="$(tput setaf 5)"
    export P_VIOLET="$(tput setaf 5)"
    export P_BLUE="$(tput setaf 4)"
    export P_CYAN="$(tput setaf 6)"
    export P_GREEN="$(tput setaf 2)"
fi
