#!/usr/bin/env python3 #--------------------------------------------------------------------------#
# AUTHOR:  Andrew Michaud                                                                         #
# FILE:    startup                                                                                #
# PURPOSE: Python Startup File                                                                    #
# UPDATED: 2016-02-22                                                                             #
# LICENSE: BSD3                                                                                   #
###################################################################################################

import atexit
import os
import readline
import rlcompleter

history_path = os.path.expandvars("$XDG_DATA_HOME/python/history")

readline.parse_and_bind("tab: complete")


def save_history(history_path=history_path):
    import readline
    readline.write_history_file(history_path)

if os.path.exists(history_path):
    readline.read_history_file(history_path)

atexit.register(save_history)
del os, atexit, readline, rlcompleter, save_history, history_path
