#!/bin/sh

CONF="$HOME/.config"

# Update Xresources
[ -f .Xresources ] && xrdb -merge .Xresources

# Set cursor style and auto-hide cursor
xsetroot -cursor_name left_ptr
unclutter &

xscreensaver -no-splash &

# Run scripts
[ -f "$HOME/.local/bin/setWallpaper" ] && "$HOME/.local/bin/setWallpaper" &
[ -f "$HOME/.local/bin/fixscreens" ] && "$HOME/.local/bin/fixscreens" &

# dbus and agents.
eval "$(dbus-launch --auto-syntax)"
eval "$(ssh-agent)"
export SSH_ASKPASS=ssh-askpass
eval "$(gnome-keyring-daemon)"

# Chat, music daemon, LastFM integration.
pgrep -x pidgin | pidgin &
[ ! -s "$CONF/mpd/pid" ] && mpd &
pgrep -x mpdscribble | mpdscribble \
    --conf "$CONF/mpdscribble/config" \
    --log "$CONF/mpdscribble/mpdscribble.log" &

mate-power-manager &

# Start mpDpris to track what MPD is doing in a standard (?) way
mpDris2 &

# notifications
pgrep -x dunst | dunst &

# Launch Taffybar and XMonad.
taffybar &
exec xmonad
